version: "3.8"
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"

  player-api:
    image: tournament-showcase:latest
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 5s
    ports:
      - "8081:8081"
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    environment:
      DB_ENDPOINT: http://dynamodb-local:8000
      PORT: 8081






